# Generated by Django 2.2.6 on 2019-11-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libFrequence', models.CharField(max_length=50)),
                ('stateFrequence', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_git', models.CharField(max_length=255, null=True)),
                ('Discord_webHook', models.CharField(max_length=255, null=True)),
                ('Slack_webHook', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RapportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_link', models.CharField(max_length=255)),
                ('frequence', models.IntegerField()),
                ('Discord_alert', models.BooleanField(default=False)),
                ('Slack_alert', models.BooleanField(default=False)),
                ('DateTimeRapport', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiUser.User')),
            ],
        ),
    ]
