# Generated by Django 3.0.2 on 2020-01-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportinfo',
            name='DateTimeRapport',
        ),
        migrations.AddField(
            model_name='rapport',
            name='dateRapport',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='rapport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiUser.RapportInfo'),
        ),
        migrations.AddField(
            model_name='rapportinfo',
            name='hasAutoReport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapportinfo',
            name='repo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rapportinfo',
            name='Discord_alert',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportinfo',
            name='Slack_alert',
            field=models.CharField(default='', max_length=255),
        ),
    ]
