# Generated by Django 3.0.2 on 2020-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUser', '0002_auto_20200111_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='dateRapport',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
