# Generated by Django 3.0.2 on 2020-01-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiUser', '0004_auto_20200112_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportinfo',
            name='frequence',
        ),
    ]
